#using yml from https://github.com/vincent8055/3.10_unit_test_secret/blob/main/.github/workflows/terraform-ci.yml


name: Terraform CI

on: [push]

jobs:
  Terraform-CI:
    name: Terraform-CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test